# Generated by Django 4.2.9 on 2024-01-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='profilepic')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('address', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
